=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/misc/component.xsd
<?xml version="1.0"?>
<xs:schema  xmlns="http://blazebit.com/jsf/component"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://blazebit.com/jsf/component"
			elementFormDefault="qualified"
   			attributeFormDefault="qualified">
   			
	<xs:element name="component" type="component"/>
	
	<xs:complexType name="component">
		<xs:sequence>
			<xs:element name="tag" type="xs:string"/>
			<xs:element name="componentClass" type="xs:string"/>
			<xs:element name="componentHandlerClass" type="xs:string" minOccurs="0"/>
			<xs:element name="componentType" type="xs:string"/>
			<xs:element name="componentFamily" type="xs:string"/>
			<xs:element name="rendererType" type="xs:string" minOccurs="0"/>
			<xs:element name="rendererClass" type="xs:string" minOccurs="0"/>
			<xs:element name="parent" type="xs:string"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="interfaces" minOccurs="0" type="interfaces"/>
			<xs:element name="attributes" minOccurs="0" type="attributes"/>
			<xs:element name="resources" minOccurs="0" type="resources"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interfaces">
		<xs:sequence>
			<xs:element name="interface" maxOccurs="unbounded" type="interface"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interface">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="attributes">
		<xs:choice maxOccurs="unbounded">
			<xs:any namespace="http://www.w3.org/2001/XInclude"/>
			<xs:element name="attribute" type="attribute"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="attribute">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="required" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="literal" type="xs:boolean" minOccurs="0"/>
			<xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
			<xs:element name="method-signature" type="xs:string" minOccurs="0"/>
			<xs:element name="ignoreInComponent" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
				
	<xs:complexType name="resources">
		<xs:sequence>
			<xs:element name="resource" maxOccurs="unbounded" type="resource"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="target" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/radioButton.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>radioButton</tag>
	<componentClass>com.blazebit.blazefaces.component.radiobutton.RadioButton</componentClass>
	<componentType>com.blazebit.blazefaces.component.RadioButton</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.RadioButtonRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.radiobutton.RadioButtonRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>disabled</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Disables the component.</description>
        </attribute>
        <attribute>
            <name>itemIndex</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <description>Index of the selectItem of the selectOneRadio.</description>
        </attribute>
        <attribute>
            <name>onchange</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute on state change.</description>
        </attribute>
        <attribute>
            <name>for</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Id of the selectOneRadio component to attach to.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required></required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required></required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
	</attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/dialog.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>dialog</tag>
    <componentClass>com.blazebit.blazefaces.component.dialog.Dialog</componentClass>
    <componentType>com.blazebit.blazefaces.component.Dialog</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.DialogRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.dialog.DialogRenderer</rendererClass>
    <parent>javax.faces.component.UIPanel</parent>
    <description>Dialog is a panel component overlaying other elements. Dialog avoids popup blockers, provides customization, resizing, modality, ajax interactions and more.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
    <attributes>
        <xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>header</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Text of the header.</description>
        </attribute>
        <attribute>
            <name>draggable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Specifies draggability. Default is true.</description>
        </attribute>
        <attribute>
            <name>resizable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Specifies resizability. Default is true.</description>
        </attribute>
        <attribute>
            <name>modal</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Boolean value that specifies whether the document should be shielded with a partially transparent mask to require the user to close the Panel before being able to activate any elements in the document. Default is false.</description>
        </attribute>
        <attribute>
            <name>visible</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Sets dialogs visibility. Default is false.</description>
        </attribute>
        <attribute>
            <name>width</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Width of the dialog in pixels. Default is auto.</description>
        </attribute>
        <attribute>
            <name>height</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Height of the dialog.</description>
        </attribute>
        <attribute>
            <name>minWidth</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
            <description>Minimum width of a resizable dialog. Default is unl.</description>
        </attribute>
        <attribute>
            <name>minHeight</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>java.lang.Integer.MIN_VALUE</defaultValue>
            <description>Minimum height of a resizable dialog. Default is height of titlebar.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the dialog container.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the dialog container.</description>
        </attribute>
        <attribute>
            <name>showEffect</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Effect to use when showing the dialog.</description>
        </attribute>
        <attribute>
            <name>hideEffect</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Effect to use when hiding the dialog.</description>
        </attribute>
        <attribute>
            <name>position</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Defines where the dialog should be displayed.</description>
        </attribute>
        <attribute>
            <name>closable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines if close icon should be displayed or not.</description>
        </attribute>
        <attribute>
            <name>onShow</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute when dialog is displayed.</description>
        </attribute>
        <attribute>
            <name>onHide</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute when dialog is hidden.</description>
        </attribute>
        <attribute>
            <name>appendToBody</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Appends dialog as a child of document body.</description>
        </attribute>
        <attribute>
            <name>showHeader</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Specifies visibility of header content.</description>
        </attribute>
        <attribute>
            <name>footer</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Text of the footer.</description>
        </attribute>
        <attribute>
            <name>dynamic</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Dynamic mode allows dialog to fetch it's contents before it's shown rather than on page load
            which is useful to reduce initial page load times. Default is false.</description>
        </attribute>
        <attribute>
            <name>minimizable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Specifies if dialog is minimizable or not. Default false.</description>
        </attribute>
        <attribute>
            <name>maximizable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Specifies if dialog is maximizable or not. Default false.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/idleMonitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>idleMonitor</tag>
    <componentClass>com.blazebit.blazefaces.component.idlemonitor.IdleMonitor</componentClass>
    <componentType>com.blazebit.blazefaces.component.IdleMonitor</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.IdleMonitorRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.idlemonitor.IdleMonitorRenderer</rendererClass>
    <parent>javax.faces.component.UIComponentBase</parent>
    <description>IdleMonitor watches user actions on a page and notify several callbacks in case they go idle or active again.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
    <attributes>
        <xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>timeout</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>300000</defaultValue>
            <description>Time to wait in milliseconds until deciding if the user is idle. Default is 5 minutes.</description>
        </attribute>
        <attribute>
            <name>onidle</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute when user goes idle.</description>
        </attribute>
        <attribute>
            <name>onactive</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute when user goes idle.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>blazefaces.js</name>
        </resource>
        <resource>
            <name>idlemonitor/idlemonitor.js</name>
        </resource>
    </resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/dataGrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>dataGrid</tag>
    <componentClass>com.blazebit.blazefaces.component.datagrid.DataGrid</componentClass>
    <componentType>com.blazebit.blazefaces.component.DataGrid</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.DataGridRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.datagrid.DataGridRenderer</rendererClass>
    <parent>com.blazebit.blazefaces.component.UIData</parent>
    <description>DataGrid displays a collection of data in grid layout. Ajax Pagination is a built-in feature and paginator UI is fully customizable via various options like paginatorTemplate, rowPerPageOptions, pageLinks and more.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
    <attributes>
        <xi:include href="./../entities/data_component_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>columns</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>3</defaultValue>
            <description>Number of columns of grid. Default is 3.</description>
        </attribute>
        <attribute>
            <name>paginator</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Enables pagination.</description>
        </attribute>
        <attribute>
            <name>paginatorTemplate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Template of the paginator.</description>
        </attribute>
        <attribute>
            <name>rowsPerPageTemplate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Template of the rowsPerPage dropdown.</description>
        </attribute>
        <attribute>
            <name>currentPageReportTemplate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Template of the currentPageReport UI.</description>
        </attribute>
        <attribute>
            <name>pageLinks</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>10</defaultValue>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Maximum number of page links to display. Default is 10.</description>
        </attribute>
        <attribute>
            <name>paginatorPosition</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>both</defaultValue>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Position of the paginator. Default is both.</description>
        </attribute>
        <attribute>
            <name>paginatorAlwaysVisible</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Defines if paginator should be hidden if total data count is less than number of rows per page. Default is true.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the main container.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the main container.</description>
        </attribute>
        <attribute>
            <name>rowIndexVar</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Name of iterator to refer each row index.</description>
        </attribute>
        <attribute>
			<name>emptyMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>No records found.</defaultValue>
            <description>Text to display when there is no data to display. Default is "No records found."</description>
		</attribute>
        <attribute>
			<name>lazy</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Defines if lazy loading is enabled for the data component.</description>
		</attribute>
    </attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/imageCompare.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>imageCompare</tag>
	<componentClass>com.blazebit.blazefaces.component.imagecompare.ImageCompare</componentClass>
	<componentType>com.blazebit.blazefaces.component.ImageCompare</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.ImageCompareRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.imagecompare.ImageCompareRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>ImageCompare provides a rich user interface to compare two images.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
    <attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>leftImage</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Source of the image placed on the left side.</description>
		</attribute>
		<attribute>
			<name>rightImage</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Source of the image placed on the right side</description>
		</attribute>
		<attribute>
			<name>width</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Width of the images.</description>
		</attribute>
		<attribute>
			<name>height</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Height of the images.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style of the image container element.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the image container element.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
		<resource>
			<name>imagecompare/imagecompare.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/rating.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>rating</tag>
    <componentClass>com.blazebit.blazefaces.component.rating.Rating</componentClass>
    <componentType>com.blazebit.blazefaces.component.Rating</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.RatingRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.rating.RatingRenderer</rendererClass>
    <parent>javax.faces.component.UIInput</parent>
    <description>Rating component features a star based rating system. Rating can be used as a plain input component or with ajax RateListeners.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
    <attributes>
        <xi:include href="./../entities/input_component_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>stars</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>5</defaultValue>
            <description>Number of stars to display. Default is 5.</description>
        </attribute>
        <attribute>
            <name>disabled</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Disables user interaction.</description>
        </attribute>
        <attribute>
            <name>readonly</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Disables user interaction without adding disabled visuals.</description>
        </attribute>
        <attribute>
            <name>onRate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Client side callback to execute when rate happens.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the component.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the component.</description>
        </attribute>
        <attribute>
            <name>cancel</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>When enabled, displays a cancel icon to reset rating value, defaults to true.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>blazefaces.css</name>
        </resource>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>blazefaces.js</name>
        </resource>
    </resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/toolbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component"
			xmlns:xi="http://www.w3.org/2001/XInclude"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>toolbar</tag>
	<componentClass>com.blazebit.blazefaces.component.toolbar.Toolbar</componentClass>
	<componentType>com.blazebit.blazefaces.component.Toolbar</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.ToolbarRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.toolbar.ToolbarRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>Toolbar is a horizontal grouping component for commands and other content.</description>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the container element.</description>
		</attribute>
        <attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the container element.</description>
		</attribute>
	</attributes>
    <resources>
		<resource>
			<name>blazefaces.css</name>
		</resource>
    </resources>
</component>
