=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/misc/component.xsd
<?xml version="1.0"?>
<xs:schema  xmlns="http://blazebit.com/jsf/component"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://blazebit.com/jsf/component"
			elementFormDefault="qualified"
   			attributeFormDefault="qualified">
   			
	<xs:element name="component" type="component"/>
	
	<xs:complexType name="component">
		<xs:sequence>
			<xs:element name="tag" type="xs:string"/>
			<xs:element name="componentClass" type="xs:string"/>
			<xs:element name="componentHandlerClass" type="xs:string" minOccurs="0"/>
			<xs:element name="componentType" type="xs:string"/>
			<xs:element name="componentFamily" type="xs:string"/>
			<xs:element name="rendererType" type="xs:string" minOccurs="0"/>
			<xs:element name="rendererClass" type="xs:string" minOccurs="0"/>
			<xs:element name="parent" type="xs:string"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="interfaces" minOccurs="0" type="interfaces"/>
			<xs:element name="attributes" minOccurs="0" type="attributes"/>
			<xs:element name="resources" minOccurs="0" type="resources"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interfaces">
		<xs:sequence>
			<xs:element name="interface" maxOccurs="unbounded" type="interface"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interface">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="attributes">
		<xs:choice maxOccurs="unbounded">
			<xs:any namespace="http://www.w3.org/2001/XInclude"/>
			<xs:element name="attribute" type="attribute"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="attribute">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="required" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="literal" type="xs:boolean" minOccurs="0"/>
			<xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
			<xs:element name="method-signature" type="xs:string" minOccurs="0"/>
			<xs:element name="ignoreInComponent" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
				
	<xs:complexType name="resources">
		<xs:sequence>
			<xs:element name="resource" maxOccurs="unbounded" type="resource"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="target" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/fieldset.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>fieldset</tag>
	<componentClass>com.blazebit.blazefaces.component.fieldset.Fieldset</componentClass>
	<componentType>com.blazebit.blazefaces.component.Fieldset</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.FieldsetRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.fieldset.FieldsetRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
    <description>Fieldset is a grouping component with a title and content.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
			<name>legend</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Title text.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the fieldset.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the fieldset.</description>
		</attribute>
         <attribute>
            <name>toggleable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Makes content toggleable with animation. Default is false.</description>
        </attribute>
        <attribute>
            <name>toggleSpeed</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>500</defaultValue>
            <description>Sets toogle animation speed in milliseconds. Default is 500.</description>
        </attribute>
        <attribute>
            <name>collapsed</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Defines initial visibility state of content. Default is false.</description>
        </attribute>
	</attributes>
	    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/defaultCommand.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>defaultCommand</tag>
    <componentClass>com.blazebit.blazefaces.component.defaultcommand.DefaultCommand</componentClass>
    <componentType>com.blazebit.blazefaces.component.DefaultCommand</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.DefaultCommandRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.defaultcommand.DefaultCommandRenderer</rendererClass>
    <parent>javax.faces.component.UIComponentBase</parent>
    <description>DefaultCommand defines the default command component to invoke when enter key is pressed in a form.</description>
    <interfaces>
        <interface>
            <name>com.blazebit.blazefaces.component.Widget</name>
        </interface>
    </interfaces>
    <attributes>
        <xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>target</name>
            <required>true</required>
            <type>java.lang.String</type>
            <description>Identifier of the default command component.</description>
        </attribute>
        <attribute>
            <name>scope</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Identifier of the grouping component to enable multiple default commands in a form.</description>
        </attribute>
    </attributes>
    <resources>
        <resource>
            <name>jquery/jquery.js</name>
        </resource>
        <resource>
            <name>blazefaces.js</name>
        </resource>
    </resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/slider.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component"
			xmlns:xi="http://www.w3.org/2001/XInclude"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>slider</tag>
	<componentClass>com.blazebit.blazefaces.component.slider.Slider</componentClass>
    <componentHandlerClass>com.blazebit.blazefaces.component.slider.SliderHandler</componentHandlerClass>
	<componentType>com.blazebit.blazefaces.component.Slider</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.SliderRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.slider.SliderRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>Slider is used to provide input with various customization options like orientation, display modes and skinning.</description>
     <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
		<interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>for</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Id of the input text that the slider will be used for.</description>
		</attribute>
		<attribute>
			<name>display</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Id of the component to display the slider value.</description>
		</attribute>
		<attribute>
			<name>minValue</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>0</defaultValue>
            <description>Minimum value of the slider. Default is 0.</description>
		</attribute>
		<attribute>
			<name>maxValue</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>100</defaultValue>
            <description>Maximum value of the slider. Default is 100.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the container element.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the container element.</description>
		</attribute>
		<attribute>
			<name>animate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>true</defaultValue>
            <description>Boolean value to enable/disable the animated move when background of slider is clicked. Default is true.</description>
		</attribute>
		<attribute>
			<name>type</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>horizontal</defaultValue>
            <description>Sets the type of the slider, "horizontal" or "vertical". Default is horizontal.</description>
		</attribute>
		<attribute>
			<name>step</name>
			<required>false</required>
			<type>java.lang.Integer</type>
			<defaultValue>1</defaultValue>
            <description>Fixed pixel increments that the slider move in. Default is 1.</description>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>Disables or enables the slider.</description>
		</attribute>
        <attribute>
			<name>onSlideStart</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Client side callback to execute when slide begins.</description>
		</attribute>
         <attribute>
			<name>onSlide</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Client side callback to execute during sliding.</description>
		</attribute>
        <attribute>
			<name>onSlideEnd</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Client side callback to execute when slide ends.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces-mobile/src/main/resources-maven-jsf/ui/buttonGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>buttonGroup</tag>
	<componentClass>com.blazebit.blazefaces.mobile.component.buttongroup.ButtonGroup</componentClass>
	<componentType>com.blazebit.blazefaces.mobile.ButtonGroup</componentType>
	<componentFamily>com.blazebit.blazefaces.mobile.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.mobile.component.ButtonGroupRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.mobile.component.buttongroup.ButtonGroupRenderer</rendererClass>
	<parent>javax.faces.component.UIPanel</parent>
	<attributes>
		<xi:include href="../entities/standard_uicomponent_attributes.xml" xpointer="xpointer(/component/attribute)"/>
        <attribute>
			<name>orientation</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>vertical</defaultValue>
		</attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
	</attributes>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/galleriaOverlay.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>galleriaOverlay</tag>
	<componentClass>com.blazebit.blazefaces.component.galleria.GalleriaOverlay</componentClass>
	<componentType>com.blazebit.blazefaces.component.GalleriaOverlay</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.GalleriaOverlayRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.galleria.GalleriaOverlayRenderer</rendererClass>
	<parent>javax.faces.component.UIColumn</parent>
    <attributes>
        <attribute>
            <name>title</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
    </attributes>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/lineChart.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>lineChart</tag>
	<componentClass>com.blazebit.blazefaces.component.chart.line.LineChart</componentClass>
	<componentType>com.blazebit.blazefaces.component.chart.LineChart</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.chart.LineChartRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.chart.line.LineChartRenderer</rendererClass>
	<parent>com.blazebit.blazefaces.component.chart.CartesianChart</parent>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>value</name>
			<required>false</required>
			<type>com.blazebit.blazefaces.model.chart.CartesianChartModel</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
			<ignoreInComponent>true</ignoreInComponent>
		</attribute>
         <attribute>
			<name>title</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendPosition</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
		<attribute>
			<name>minY</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MIN_VALUE</defaultValue>
		</attribute>
		<attribute>
			<name>maxY</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MAX_VALUE</defaultValue>
		</attribute>
        <attribute>
			<name>minX</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MIN_VALUE</defaultValue>
		</attribute>
		<attribute>
			<name>maxX</name>
			<required>false</required>
			<type>java.lang.Double</type>
			<defaultValue>java.lang.Double.MAX_VALUE</defaultValue>
		</attribute>
        <attribute>
			<name>breakOnNull</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>seriesColors</name>
			<required>false</required>
			<type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>shadow</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
       <attribute>
			<name>fill</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
       <attribute>
			<name>stacked</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
       <attribute>
			<name>showMarkers</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
		</attribute>
       <attribute>
			<name>xaxisLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>yaxisLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>xaxisAngle</name>
			<required>false</required>
			<type>java.lang.Integer</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>yaxisAngle</name>
			<required>false</required>
			<type>java.lang.Integer</type>
        <ignoreInComponent>true</ignoreInComponent>
		</attribute>
        <attribute>
			<name>legendCols</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Defines visible column count of chart legend.</description>
		</attribute>
        <attribute>
			<name>legendRows</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Defines visible row count of chart legend.</description>
		</attribute>
        <attribute>
			<name>zoom</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables plot zooming.</description>
		</attribute>
        <attribute>
			<name>extender</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>Javascript function to extend the chart with low level jqplot options.</description>
		</attribute>
        <attribute>
			<name>animate</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables animation on plot, default is false.</description>
		</attribute>
        <attribute>
			<name>showDatatip</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines visibility of datatip, default is true.</description>
		</attribute>
        <attribute>
			<name>datatipFormat</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Template string for datatips.</description>
		</attribute>
	</attributes>
	<resources>
        <resource>
			<name>charts/charts.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
		<resource>
			<name>charts/charts.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/rowExpansion.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>rowExpansion</tag>
	<componentClass>com.blazebit.blazefaces.component.rowexpansion.RowExpansion</componentClass>
	<componentType>com.blazebit.blazefaces.component.RowExpansion</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<parent>javax.faces.component.UIColumn</parent>
    <description>RowExpansion is a helper component of datatable used to implement expandable rows.</description>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
	</attributes>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/orderList.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>orderList</tag>
	<componentClass>com.blazebit.blazefaces.component.orderlist.OrderList</componentClass>
	<componentType>com.blazebit.blazefaces.component.OrderList</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.OrderListRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.orderlist.OrderListRenderer</rendererClass>
	<parent>javax.faces.component.UIInput</parent>
    <description>OrderList is used to sort a collection.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/input_component_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>var</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Name of the iterator.</description>
		</attribute>
		<attribute>
			<name>itemLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of an item.</description>
		</attribute>
		<attribute>
			<name>itemValue</name>
			<required>false</required>
			<type>java.lang.Object</type>
            <description>Value of an item.</description>
		</attribute>
		<attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style of the main container.</description>
		</attribute>
		<attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the main container.</description>
		</attribute>
		<attribute>
			<name>disabled</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>Disables the component.</description>
		</attribute>
        <attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Name of the animation to display. Default is fade.</description>
		</attribute>
        <attribute>
			<name>moveUpLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Up</defaultValue>
            <description>Text of move up button. Default is "Move Up".</description>
		</attribute>
        <attribute>
			<name>moveTopLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Top</defaultValue>
            <description>Text of move top button. Default is "Move Top".</description>
		</attribute>
        <attribute>
			<name>moveDownLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Down</defaultValue>
            <description>Text of move down button. Default is "Move Down".</description>
		</attribute>
        <attribute>
			<name>moveBottomLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>Move Bottom</defaultValue>
            <description>Text of move bottom button. Default is "Move Down".</description>
		</attribute>
        <attribute>
			<name>controlsLocation</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>left</defaultValue>
            <description>Location of the order controls, valid values are "left" (default), "right" and none.</description>
		</attribute>
	</attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>
