=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/misc/component.xsd
<?xml version="1.0"?>
<xs:schema  xmlns="http://blazebit.com/jsf/component"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://blazebit.com/jsf/component"
			elementFormDefault="qualified"
   			attributeFormDefault="qualified">
   			
	<xs:element name="component" type="component"/>
	
	<xs:complexType name="component">
		<xs:sequence>
			<xs:element name="tag" type="xs:string"/>
			<xs:element name="componentClass" type="xs:string"/>
			<xs:element name="componentHandlerClass" type="xs:string" minOccurs="0"/>
			<xs:element name="componentType" type="xs:string"/>
			<xs:element name="componentFamily" type="xs:string"/>
			<xs:element name="rendererType" type="xs:string" minOccurs="0"/>
			<xs:element name="rendererClass" type="xs:string" minOccurs="0"/>
			<xs:element name="parent" type="xs:string"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="interfaces" minOccurs="0" type="interfaces"/>
			<xs:element name="attributes" minOccurs="0" type="attributes"/>
			<xs:element name="resources" minOccurs="0" type="resources"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interfaces">
		<xs:sequence>
			<xs:element name="interface" maxOccurs="unbounded" type="interface"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="interface">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="attributes">
		<xs:choice maxOccurs="unbounded">
			<xs:any namespace="http://www.w3.org/2001/XInclude"/>
			<xs:element name="attribute" type="attribute"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="attribute">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="required" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="literal" type="xs:boolean" minOccurs="0"/>
			<xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
			<xs:element name="method-signature" type="xs:string" minOccurs="0"/>
			<xs:element name="ignoreInComponent" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
				
	<xs:complexType name="resources">
		<xs:sequence>
			<xs:element name="resource" maxOccurs="unbounded" type="resource"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="target" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/galleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>galleria</tag>
	<componentClass>com.blazebit.blazefaces.component.galleria.Galleria</componentClass>
	<componentType>com.blazebit.blazefaces.component.Galleria</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.GalleriaRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.galleria.GalleriaRenderer</rendererClass>
	<parent>com.blazebit.blazefaces.component.UIData</parent>
    <description>Galleria is used to display a set of images.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>value</name>
            <required>true</required>
            <type>java.lang.Object</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description></description>
        </attribute>
        <attribute>
            <name>var</name>
            <required>true</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description></description>
        </attribute>
         <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the container element.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the container element.</description>
        </attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>crossfade</defaultValue>
            <description>Name of animation to use on galleria switches. Default is crossfade.</description>
		</attribute>
        <attribute>
			<name>effectSpeed</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>800</defaultValue>
            <description>Duration of animation in milliseconds. Default is 800.</description>
		</attribute>
        <attribute>
			<name>panelWidth</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>600</defaultValue>
		</attribute>
        <attribute>
			<name>panelHeight</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>400</defaultValue>
		</attribute>
        <attribute>
			<name>frameWidth</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>60</defaultValue>
		</attribute>
        <attribute>
			<name>frameHeight</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>40</defaultValue>
		</attribute>
        <attribute>
			<name>filmstripStyle</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>filmstripPosition</name>
			<required>false</required>
			<type>java.lang.String</type>
		</attribute>
        <attribute>
			<name>showFilmstrip</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
		</attribute>
        <attribute>
			<name>showCaptions</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>showOverlays</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
		</attribute>
        <attribute>
			<name>transitionInterval</name>
			<required>false</required>
			<type>java.lang.Integer</type>
            <defaultValue>4000</defaultValue>
		</attribute>
	</attributes>
	<resources>
        <resource>
			<name>galleria/galleria.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
        <resource>
			<name>galleria/galleria.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/submenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component"
			xmlns:xi="http://www.w3.org/2001/XInclude"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>submenu</tag>
	<componentClass>com.blazebit.blazefaces.component.submenu.Submenu</componentClass>
	<componentType>com.blazebit.blazefaces.component.Submenu</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>Submenu is nested in menu components and represents a sub menu items.</description>
	<interfaces>
		<interface>
			<name>java.io.Serializable</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>label</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of the submenu header.</description>
		</attribute>
        <attribute>
			<name>icon</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Icon of a submenu, see menuitem to see how it is used.</description>
		</attribute>
        <attribute>
			<name>style</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Inline style of the menu.</description>
		</attribute>
        <attribute>
			<name>styleClass</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Style class of the submenu.</description>
		</attribute>
	</attributes>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/keyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>keyboard</tag>
	<componentClass>com.blazebit.blazefaces.component.keyboard.Keyboard</componentClass>
	<componentType>com.blazebit.blazefaces.component.Keyboard</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.KeyboardRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.keyboard.KeyboardRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlInputText</parent>
    <description>Keyboard is an input component that uses a virtual keyboard to provide the input. Notable features are the customizable layouts and skinning capabilities.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/input_component_attributes.xml" parse="text"/>
		<xi:include href="./../entities/html_input_text_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>password</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>Makes the input a password field. Default is false.</description>
		</attribute>
		<attribute>
			<name>showMode</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>focus</defaultValue>
            <description>Specifies the showMode, 'focus', 'button', 'both'</description>
		</attribute>
		<attribute>
			<name>buttonImage</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Image for the button.</description>
		</attribute>
		<attribute>
			<name>buttonImageOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>When set to true only image of the button would be displayed. Default is false.</description>
		</attribute>
		<attribute>
			<name>effect</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>fadeIn</defaultValue>
            <description>Effect of the display animation. Default is fadeIn</description>
		</attribute>
		<attribute>
			<name>effectDuration</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Length of the display animation.</description>
		</attribute>
		<attribute>
			<name>layout</name>
			<required>false</required>
			<type>java.lang.String</type>
			<defaultValue>qwerty</defaultValue>
            <description>Built-in layout of the keyboard. Default is qwerty.</description>
		</attribute>
		<attribute>
			<name>layoutTemplate</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Template of the custom layout.</description>
		</attribute>
		<attribute>
			<name>keypadOnly</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
			<defaultValue>false</defaultValue>
            <description>Specifies displaying a keypad instead of a keyboard. Default is false.</description>
		</attribute>
		<attribute>
			<name>promptLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of the prompt text.</description>
		</attribute>
		<attribute>
			<name>closeLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of the close key.</description>
		</attribute>
		<attribute>
			<name>clearLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of the clear key.</description>
		</attribute>
		<attribute>
			<name>backspaceLabel</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Label of the backspace key.</description>
		</attribute>
	</attributes>
	<resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
        <resource>
			<name>keyboard/keyboard.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
		<resource>
			<name>keyboard/keyboard.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/socket.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component"
			xmlns:xi="http://www.w3.org/2001/XInclude"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>socket</tag>
	<componentClass>com.blazebit.blazefaces.component.socket.Socket</componentClass>
	<componentType>com.blazebit.blazefaces.component.Socket</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.SocketRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.socket.SocketRenderer</rendererClass>
	<parent>javax.faces.component.UIComponentBase</parent>
    <description>Socket component is an agent that creates a channel between the server and the client.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
		<attribute>
			<name>channel</name>
			<required>true</required>
			<type>java.lang.String</type>
            <description>Channel name of the connection.</description>
		</attribute>
        <attribute>
			<name>transport</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>websocket</defaultValue>
            <description>Desired protocol to be used valid values are websocket (default), sse, streaming, long-polling, jsonp. Default is websocket.</description>
		</attribute>
		<attribute>
			<name>fallbackTransport</name>
			<required>false</required>
			<type>java.lang.String</type>
            <defaultValue>long-polling</defaultValue>
            <description>Desired protocol to be used valid values are websocket, sse, streaming, long-polling (default), jsonp. Default is websocket.</description>
		</attribute>
		<attribute>
			<name>onMessage</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Javascript event handler that is processed when the server publishes data.</description>
		</attribute>
        <attribute>
			<name>onError</name>
			<required>false</required>
			<type>java.lang.String</type>
            <description>Javascript event handler that is processed when there is an error.</description>
		</attribute>
        <attribute>
			<name>autoConnect</name>
			<required>false</required>
			<type>java.lang.Boolean</type>
            <defaultValue>true</defaultValue>
            <description>Defines if client should connect to the channel on page load.</description>
		</attribute>
	</attributes>
	<resources>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
        <resource>
            <name>push/push.js</name>
        </resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/selectOneMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component"
			xmlns:xi="http://www.w3.org/2001/XInclude"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>selectOneMenu</tag>
	<componentClass>com.blazebit.blazefaces.component.selectonemenu.SelectOneMenu</componentClass>
	<componentType>com.blazebit.blazefaces.component.SelectOneMenu</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.SelectOneMenuRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.selectonemenu.SelectOneMenuRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlSelectOneMenu</parent>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/input_component_attributes.xml" parse="text"/>
		<xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>effect</name>
            <required>false</required>
            <type>java.lang.String</type>
            <defaultValue>fade</defaultValue>
        </attribute>
        <attribute>
            <name>effectSpeed</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>disabled</name>
            <required></required>
            <type>boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>label</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>onchange</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>style</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>panelStyle</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>panelStyleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>var</name>
            <required>false</required>
            <type>java.lang.String</type>
        </attribute>
        <attribute>
            <name>height</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>java.lang.Integer.MAX_VALUE</defaultValue>
        </attribute>
        <attribute>
            <name>tabindex</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>editable</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
        </attribute>
        <attribute>
            <name>onkeydown</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>onkeyup</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
	</attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/selectBooleanCheckbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
	<tag>selectBooleanCheckbox</tag>
	<componentClass>com.blazebit.blazefaces.component.selectbooleancheckbox.SelectBooleanCheckbox</componentClass>
	<componentType>com.blazebit.blazefaces.component.SelectBooleanCheckbox</componentType>
	<componentFamily>com.blazebit.blazefaces.component</componentFamily>
	<rendererType>com.blazebit.blazefaces.component.SelectBooleanCheckboxRenderer</rendererType>
	<rendererClass>com.blazebit.blazefaces.component.selectbooleancheckbox.SelectBooleanCheckboxRenderer</rendererClass>
	<parent>javax.faces.component.html.HtmlSelectBooleanCheckbox</parent>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
	</interfaces>
	<attributes>
		<xi:include href="./../entities/input_component_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>disabled</name>
            <required></required>
            <type>boolean</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>label</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>onchange</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>style</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required></required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
        </attribute>
        <attribute>
            <name>itemLabel</name>
            <required></required>
            <type>java.lang.String</type>
            <description>Label to display next to checkbox.</description>
        </attribute>
        <attribute>
            <name>tabindex</name>
            <required>false</required>
            <type>java.lang.String</type>
            <ignoreInComponent>true</ignoreInComponent>
            <description>The tabindex attribute specifies the tab order of an element when the "tab" button is used for navigating.</description>
        </attribute>
	</attributes>
    <resources>
        <resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
        <resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>

=== Blazebit/blaze-faces/blaze-faces/src/main/resources-maven-jsf/ui/progressBar.xml
<?xml version="1.0" encoding="UTF-8"?>
<component  xmlns="http://blazebit.com/jsf/component" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blazebit.com/jsf/component ../misc/component.xsd">
    <tag>progressBar</tag>
    <componentClass>com.blazebit.blazefaces.component.progressbar.ProgressBar</componentClass>
    <componentType>com.blazebit.blazefaces.component.ProgressBar</componentType>
    <componentFamily>com.blazebit.blazefaces.component</componentFamily>
    <rendererType>com.blazebit.blazefaces.component.ProgressBarRenderer</rendererType>
    <rendererClass>com.blazebit.blazefaces.component.progressbar.ProgressBarRenderer</rendererClass>
    <parent>javax.faces.component.UIComponentBase</parent>
    <description>ProgressBar is a process status indicator that can either work purely on client side or interact with server side using ajax.</description>
    <interfaces>
		<interface>
			<name>com.blazebit.blazefaces.component.Widget</name>
		</interface>
        <interface>
			<name>javax.faces.component.behavior.ClientBehaviorHolder</name>
		</interface>
	</interfaces>
    <attributes>
        <xi:include href="./../entities/standard_uicomponent_attributes.xml" parse="text"/>
        <xi:include href="./../entities/widget_var_attribute.xml" parse="text"/>
        <attribute>
            <name>value</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>0</defaultValue>
            <description>Value of the progress bar. Default is 0.</description>
        </attribute>
        <attribute>
            <name>disabled</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Disables or enables the progressbar.</description>
        </attribute>
        <attribute>
            <name>ajax</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Specifies the mode of progressBar, in ajax mode progress value is retrieved from a backing bean. Default is false.</description>
        </attribute>
        <attribute>
            <name>interval</name>
            <required>false</required>
            <type>java.lang.Integer</type>
            <defaultValue>3000</defaultValue>
            <description>Interval in seconds to do periodic requests in ajax mode. Default is 300.</description>
        </attribute>
        <attribute>
            <name>style</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Inline style of the main container element.</description>
        </attribute>
        <attribute>
            <name>styleClass</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Style class of the main container element.</description>
        </attribute>
        <attribute>
            <name>labelTemplate</name>
            <required>false</required>
            <type>java.lang.String</type>
            <description>Template of the progress value e.g. "{value}%"</description>
        </attribute>
        <attribute>
            <name>displayOnly</name>
            <required>false</required>
            <type>java.lang.Boolean</type>
            <defaultValue>false</defaultValue>
            <description>Enables static value display mode.</description>
        </attribute>
    </attributes>
	<resources>
		<resource>
			<name>blazefaces.css</name>
		</resource>
		<resource>
			<name>jquery/jquery.js</name>
		</resource>
		<resource>
			<name>blazefaces.js</name>
		</resource>
	</resources>
</component>
